--@Autores:     Jorge Manzanares y Jesús Salazar
--@Fecha:       21/05/2023
--@Descripción: Crea tablas y restricciones para el sitio JSDBD_S1

SET SERVEROUTPUT ON
DECLARE
  CURSOR CUR_TABLES IS 
    SELECT TABLE_NAME FROM USER_TABLES;
BEGIN
  FOR T IN CUR_TABLES LOOP
    DBMS_OUTPUT.PUT_LINE('ELIMINANDO LA TABLA => ' || T.TABLE_NAME);
    EXECUTE IMMEDIATE 'DROP TABLE ' || T.TABLE_NAME || ' CASCADE CONSTRAINTS';
  END LOOP;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERROR, EXCEPCIÓN INESPERADA => ' || TO_CHAR(SQLCODE));
    DBMS_OUTPUT.PUT_LINE('ERROR => ' || SQLERRM);
END;
/
-- 
-- TABLE: ARCHIVO_PROGRAMA_F2_JSD_S1 
--

CREATE TABLE ARCHIVO_PROGRAMA_F2_JSD_S1(
    NUM_ARCHIVO    NUMBER(5, 0)     NOT NULL,
    PROGRAMA_ID    NUMBER(10, 0)    NOT NULL,
    ARCHIVO        BLOB             NOT NULL,
    TAMANIO        NUMBER(10, 2)    NOT NULL,
    CONSTRAINT ARCHIVO_PROGRAMA_F2_JSD_S1_PK PRIMARY KEY (NUM_ARCHIVO, PROGRAMA_ID)
)
;



-- 
-- TABLE: PAIS_R_JSD_S1 
--

CREATE TABLE PAIS_R_JSD_S1(
    PAIS_ID       NUMBER(2, 0)    NOT NULL,
    CLAVE         VARCHAR2(4)     NOT NULL,
    NOMBRE        VARCHAR2(50)    NOT NULL,
    CONTINENTE    VARCHAR2(3)     NOT NULL,
    CONSTRAINT PAIS_R_JSD_S1_PK PRIMARY KEY (PAIS_ID)
)
;



-- 
-- TABLE: STATUS_PROGRAMA_JSD_S1 
--

CREATE TABLE STATUS_PROGRAMA_JSD_S1(
    STATUS_PROGRAMA_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE                 VARCHAR2(40)     NOT NULL,
    DESCRIPCION           VARCHAR2(500)    NOT NULL,
    CONSTRAINT STATUS_PROGRAMA_JSD_S1_PK PRIMARY KEY (STATUS_PROGRAMA_ID)
)
;



-- 
-- TABLE: PROGRAMA_F2_JSD_S1 
--

CREATE TABLE PROGRAMA_F2_JSD_S1(
    PROGRAMA_ID           NUMBER(10, 0)    NOT NULL,
    FOLIO                 VARCHAR2(13)     NOT NULL,
    NOMBRE                VARCHAR2(100)    NOT NULL,
    DESCRIPCION           VARCHAR2(500)    NOT NULL,
    FECHA_STATUS          DATE             NOT NULL,
    TIPO                  CHAR(1)          NOT NULL,
    STATUS_PROGRAMA_ID    NUMBER(2, 0)     NOT NULL,
    CONSTRAINT PROGRAMA_F2_JSD_S1_PK                    PRIMARY KEY (PROGRAMA_ID), 
    CONSTRAINT PROGRAMA_F2_JSD_S1_STATUS_PROGRAMA_FK    FOREIGN KEY (STATUS_PROGRAMA_ID)
      REFERENCES STATUS_PROGRAMA_JSD_S1(STATUS_PROGRAMA_ID)
)
;



-- 
-- TABLE: DOCUMENTAL_F2_JSD_S1 
--

CREATE TABLE DOCUMENTAL_F2_JSD_S1(
    PROGRAMA_ID    NUMBER(10, 0)    NOT NULL,
    TEMATICA       VARCHAR2(100)    NOT NULL,
    DURACION       NUMBER(5, 2)     NOT NULL,
    TRAILER        BLOB             NOT NULL,
    PAIS_ID        NUMBER(2, 0)     NOT NULL,
    CONSTRAINT DOCUMENTAL_F2_JSD_S1_PK          PRIMARY KEY (PROGRAMA_ID), 
    CONSTRAINT DOCUMENTAL_F2_JSD_S1_PAIS_FK     FOREIGN KEY (PAIS_ID)
      REFERENCES PAIS_R_JSD_S1(PAIS_ID),
    CONSTRAINT DOCUMENTAL_F2_JSD_S1_PROGRAMA_FK FOREIGN KEY (PROGRAMA_ID)
      REFERENCES PROGRAMA_F2_JSD_S1(PROGRAMA_ID)
)
;



-- 
-- TABLE: PELICULA_F2_JSD_S1 
--

CREATE TABLE PELICULA_F2_JSD_S1(
    PROGRAMA_ID                NUMBER(10, 0)    NOT NULL,
    PELICULA_ANTECEDENTE_ID    NUMBER(10, 0)    ,
    DURACION                   NUMBER(5, 2)     NOT NULL,
    SINOPSIS                   VARCHAR2(500)    NOT NULL,
    CLASIFICACION              CHAR(1)          NOT NULL,
    CONSTRAINT PELICULA_F2_JSD_S1_PK            PRIMARY KEY (PROGRAMA_ID), 
    CONSTRAINT PELICULA_F2_JSD_S1_PROGRMA_FK    FOREIGN KEY (PROGRAMA_ID)
      REFERENCES PROGRAMA_F2_JSD_S1(PROGRAMA_ID)
)
;



-- 
-- TABLE: TIPO_CUENTA_R_JSD_S1 
--

CREATE TABLE TIPO_CUENTA_R_JSD_S1(
    TIPO_CUENTA_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE             VARCHAR2(40)     NOT NULL,
    DESCRIPCION       VARCHAR2(500)    NOT NULL,
    COSTO_MENSUAL     NUMBER(10, 2)    NOT NULL,
    CONSTRAINT TIPO_CUENTA_R_JSD_S1_PK PRIMARY KEY (TIPO_CUENTA_ID)
)
;



-- 
-- TABLE: USUARIO_F4_JSD_S1 
--

CREATE TABLE USUARIO_F4_JSD_S1(
    USUARIO_ID          NUMBER(10, 0)    NOT NULL,
    EMAIL               VARCHAR2(200)    NOT NULL,
    NOMBRE              VARCHAR2(40)     NOT NULL,
    AP_PATERNO          VARCHAR2(40)     NOT NULL,
    AP_MATERNO          VARCHAR2(40)     NOT NULL,
    FECHA_INGRESO       DATE,
    FECHA_CUENTA_FIN    DATE,
    VIGENTE             NUMBER(1, 0)     NOT NULL,
    TIPO_CUENTA_ID      NUMBER(2, 0)     NOT NULL,
    CONSTRAINT USUARIO_F4_JSD_S1_PK             PRIMARY KEY (USUARIO_ID), 
    CONSTRAINT USUARIO_F4_JSD_S1_TIPO_CUENTA_FK FOREIGN KEY (TIPO_CUENTA_ID)
      REFERENCES TIPO_CUENTA_R_JSD_S1(TIPO_CUENTA_ID)
)
;



-- 
-- TABLE: PLAYLIST_F3_JSD_S1 
--

CREATE TABLE PLAYLIST_F3_JSD_S1(
    PLAYLIST_ID           NUMBER(10, 0)    NOT NULL,
    PROGRAMA_ID           NUMBER(10, 0)    NOT NULL,
    CALIFICACION           NUMBER(1, 0)     NOT NULL,
    INDICE                NUMBER(10, 0)    NOT NULL,
    NUM_REPRODUCCIONES    NUMBER(10, 0)    NOT NULL,
    USUARIO_ID            NUMBER(10, 0)    NOT NULL,
    CONSTRAINT PLAYLIST_F3_JSD_S1_PK            PRIMARY KEY (PLAYLIST_ID), 
    CONSTRAINT PLAYLIST_F3_JSD_S1_USUARIO_FK    FOREIGN KEY (USUARIO_ID)
      REFERENCES USUARIO_F4_JSD_S1(USUARIO_ID)
)
;



-- 
-- TABLE: TIPO_SERIE_R_JSD_S1 
--

CREATE TABLE TIPO_SERIE_R_JSD_S1(
    TIPO_SERIE_ID    NUMBER(2, 0)     NOT NULL,
    CLAVE            VARCHAR2(40)     NOT NULL,
    DESCRIPCION      VARCHAR2(500)    NOT NULL,
    CONSTRAINT TIPO_SERIE_R_JSD_S1_PK PRIMARY KEY (TIPO_SERIE_ID)
)
;



-- 
-- TABLE: SERIE_F2_JSD_S1 
--

CREATE TABLE SERIE_F2_JSD_S1(
    PROGRAMA_ID          NUMBER(10, 0)    NOT NULL,
    NUM_CAPITULOS        NUMBER(3, 0)     NOT NULL,
    DURACION_CAPITULO    NUMBER(5, 2)     NOT NULL,
    TIPO_SERIE_ID        NUMBER(2, 0)     NOT NULL,
    CONSTRAINT SERIE_F2_JSD_S1_PK               PRIMARY KEY (PROGRAMA_ID), 
    CONSTRAINT SERIE_F2_JSD_S1_TIPO_SERIE_FK    FOREIGN KEY (TIPO_SERIE_ID)
      REFERENCES TIPO_SERIE_R_JSD_S1(TIPO_SERIE_ID),
    CONSTRAINT SERIE_F2_JSD_S1_PROGRAMA_FK      FOREIGN KEY (PROGRAMA_ID)
      REFERENCES PROGRAMA_F2_JSD_S1(PROGRAMA_ID)
)
;



-- 
-- TABLE: USUARIO_F1_JSD_F1 
--

CREATE TABLE USUARIO_F1_JSD_S1(
    USUARIO_ID     NUMBER(10, 0)    NOT NULL,
    NUM_TARJETA    VARCHAR2(16)     NOT NULL,
    PASSWORD       VARCHAR2(16)     NOT NULL,
    CONSTRAINT USUARIO_F1_JSD_S1_PK PRIMARY KEY (USUARIO_ID)
)
;



